restaurants = {'China Xiang': {
'Id': 212011,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'44 & X': {
'Id': 105019,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 454, 'Name': 'Hell\'s Kitchen' } },
'XyZ Pintxos y Botanas': {
'Id': 212533,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 204, 'Name': 'East Village' } },
'Mission Chinese Food X': {
'Id': 246613,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 655, 'Name': 'Lower East Side' } },
'Xicala': {
'Id': 235666,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 798, 'Name': 'NoLita' } },
'XIXA': {
'Id': 189523,
'Type': 'Restaurant',
'Region': { 'Id': 24, 'Name': 'Brooklyn' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 2774, 'Name': 'Williamsburg' } },
'Xe Lua Vietnamese Restaurant': {
'Id': 101932,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 4184, 'Name': 'Chinatown' } },
'Xahar Thai': {
'Id': 192187,
'Type': 'Restaurant',
'Region': { 'Id': 17, 'Name': 'Queens' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 13043, 'Name': 'Ozone Park' } },
'X2O Xaviars on the Hudson': {
'Id': 18019,
'Type': 'Restaurant',
'Region': { 'Id': 20, 'Name': 'Westchester / Hudson Valley' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 3068, 'Name': 'Yonkers' } },
'XIN': {
'Id': 247918,
'Type': 'Restaurant',
'Region': { 'Id': 24, 'Name': 'Brooklyn' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 2783, 'Name': 'Bay Ridge' } },
'Restaurant X & Bully Boy Bar': {
'Id': 18016,
'Type': 'Restaurant',
'Region': { 'Id': 20, 'Name': 'Westchester / Hudson Valley' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 3128, 'Name': 'Congers' } },
'XO Creperie': {
'Id': 237451,
'Type': 'Restaurant',
'Region': { 'Id': 24, 'Name': 'Brooklyn' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 5330, 'Name': 'Sheepshead Bay' } },
'Xocolatz': {
'Id': 226795,
'Type': 'Restaurant',
'Region': { 'Id': 22, 'Name': 'New Jersey - North' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 733, 'Name': 'Westfield' } },
'Xochitl': {
'Id': 29113,
'Type': 'Restaurant',
'Region': { 'Id': 41, 'Name': 'Philadelphia' },
'Metro': { 'Id': 13, 'Name': 'Philadelphia / New Jersey Suburbs' },
'Country': 'United States',
'Neighborhood': { 'Id': 216, 'Name': 'Center City' } },
'XIX Nineteen': {
'Id': 3001,
'Type': 'Restaurant',
'Region': { 'Id': 41, 'Name': 'Philadelphia' },
'Metro': { 'Id': 13, 'Name': 'Philadelphia / New Jersey Suburbs' },
'Country': 'United States',
'Neighborhood': { 'Id': 216, 'Name': 'Center City' } },
'Zuma Japanese Restaurant - NY': {
'Id': 162010,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Ziya': {
'Id': 255073,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'BXL ZOUTE': {
'Id': 101122,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Trattoria Zero Otto Nove': {
'Id': 89980,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Zengo - NYC': {
'Id': 43783,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Zagara Restaurant and Wine Bar': {
'Id': 114055,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Zio': {
'Id': 64360,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Zora\'s Cafe': {
'Id': 332881,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 454, 'Name': 'Hell\'s Kitchen' } },
'Kuruma Zushi': {
'Id': 278182,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Sushi Zen - Permanently Closed': {
'Id': 189448,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Au Za\'atar': {
'Id': 118177,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 204, 'Name': 'East Village' } },
'Double Zero': {
'Id': 212734,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 204, 'Name': 'East Village' } },
'ZZ\'S Clam Bar': {
'Id': 157231,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 111, 'Name': 'Greenwich Village' } },
'Le Zie 2000': {
'Id': 238768,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 412, 'Name': 'West Village' } },
'Zabb City': {
'Id': 243082,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 443, 'Name': 'Union Square' } },
'Osamil': {
'Id': 333829,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'O\'Reilly\'s Bar & Kitchen': {
'Id': 95806,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'O\'Reilly\'s Pub': {
'Id': 211501,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'L&W Oyster Co': {
'Id': 96586,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'o ya - NYC': {
'Id': 167146,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Sushi Ginza Onodera': {
'Id': 258580,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'OCabanon': {
'Id': 126826,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Osteria del Principe': {
'Id': 89680,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Trattoria Zero Otto Nove': {
'Id': 89980,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Obica Mozzarella Bar  Pizza e Cucina': {
'Id': 146161,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Grand Central Oyster Bar': {
'Id': 179,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Docks Oyster Bar and Seafood Grill': {
'Id': 35893,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Sala One Nine': {
'Id': 33700,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Osteria al Doge': {
'Id': 4568,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Osteria Laguna': {
'Id': 12196,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'The Vine': {
'Id': 88648,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Strand Bistro at Marriott Vacation Club Pulse': {
'Id': 47467,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'28th Street Tarallucci e Vino': {
'Id': 261748,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Villa Berulia': {
'Id': 242167,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Vezzo': {
'Id': 242230,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'VinoTapa': {
'Id': 73891,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Madison & Vine': {
'Id': 19306,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Vago Restaurant': {
'Id': 270721,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Vatan Indian Restaurant': {
'Id': 28141,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Via Emilia': {
'Id': 107806,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Virgil\'s Real BBQ': {
'Id': 2298,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Mari Vanna': {
'Id': 34735,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Thai Villa': {
'Id': 334744,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Bobby Van\'s Grill Times Square': {
'Id': 51016,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'VITAE': {
'Id': 77257,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Jack Demsey\'s': {
'Id': 242350,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'Don\'s Bogam BBQ & Wine Bar': {
'Id': 111265,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'The Den - Hyatt Herald Square': {
'Id': 172762,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Paul\'s Dancing Cafe': {
'Id': 109585,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Cho Dang Gol Korean Restaurant': {
'Id': 237985,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'The Morgan Dining Room': {
'Id': 113266,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'John Doe Bar & Kitchen': {
'Id': 211981,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Deweys Pub': {
'Id': 170032,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'David Burke fabrick': {
'Id': 144487,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Hyo Dong Gak': {
'Id': 237601,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'Calle Dao': {
'Id': 149428,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Dee Daa - Permanently Closed': {
'Id': 261421,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Dos Caminos - Park': {
'Id': 30496,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Delmonico\'s Kitchen': {
'Id': 38689,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Wine Disciples Enoteca - Permanently Closed': {
'Id': 174346,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Monarch Rooftop Lounge': {
'Id': 172018,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Toledo Restaurant': {
'Id': 144997,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Reichenbach Hall': {
'Id': 171676,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Rocco Steakhouse': {
'Id': 19300,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Asellina Ristorante': {
'Id': 54601,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Refinery Rooftop': {
'Id': 170911,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Toshi\'s Living Room & Penthouse': {
'Id': 139150,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Zuma Japanese Restaurant - NY': {
'Id': 162010,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Resto': {
'Id': 20512,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Arno Ristorante': {
'Id': 21577,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Raymi': {
'Id': 41734,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Junoon Main Dining Room': {
'Id': 54115,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'La Mesa de Paul Restaurant @ The Paul Hotel NYC': {
'Id': 190897,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Junoon Patiala Room': {
'Id': 265027,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'RARE Bar & Grill (Murray Hill)': {
'Id': 187999,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'IchiUmi - NYC': {
'Id': 211564,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Cuisine\'s at Holiday Inn Midtown': {
'Id': 229876,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'ilili': {
'Id': 15550,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Izakaya NoMad': {
'Id': 149746,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Impero Caffe by Scott Conant': {
'Id': 215056,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Chop Shop II': {
'Id': 168136,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'I Trulli': {
'Id': 124,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Bhatti Indian Grill': {
'Id': 47656,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Shay & Ivy': {
'Id': 271216,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Mira Sushi & Izakaya Bar': {
'Id': 92797,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Vatan Indian Restaurant': {
'Id': 28141,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Amore Cafe - Holiday Inn': {
'Id': 255151,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Italienne': {
'Id': 300160,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Inakaya': {
'Id': 29497,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Trattoria Il Mulino': {
'Id': 17311,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'State Grill and Bar': {
'Id': 150565,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Statler Grill': {
'Id': 52453,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Rowland\'s Bar & Grill': {
'Id': 192205,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Bryant Park Grill': {
'Id': 12019,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Bhatti Indian Grill': {
'Id': 47656,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'RARE Bar & Grill (Murray Hill)': {
'Id': 187999,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Rare Bar and Grill': {
'Id': 48970,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Gabriel Kreuther': {
'Id': 186475,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'El Rio Grande': {
'Id': 16822,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Galata': {
'Id': 333424,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Uncle Nick\'s Greek Cuisine - Chelsea': {
'Id': 67096,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Sagaponack Bar and Grill': {
'Id': 45877,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Giorgio\'s of Gramercy': {
'Id': 11560,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Grand Central Oyster Bar': {
'Id': 179,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Gramercy Tavern': {
'Id': 942,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'State Grill and Bar': {
'Id': 150565,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Heartland Brewery - Empire State Building': {
'Id': 148705,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Soju Haus': {
'Id': 270343,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 523, 'Name': 'NoMad' } },
'Up on 20 - Hyatt Herald Square': {
'Id': 173974,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'The Den - Hyatt Herald Square': {
'Id': 172762,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Keens Steakhouse': {
'Id': 450,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Statler Grill': {
'Id': 52453,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Frankie & Johnnie\'s Steakhouse - Manhattan': {
'Id': 2792,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Wolfgang\'s Steak House - Park Avenue': {
'Id': 3603,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Strand Bistro at Marriott Vacation Club Pulse': {
'Id': 47467,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Rocco Steakhouse': {
'Id': 19300,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Staghorn Steakhouse': {
'Id': 10417,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Smorgas Chef @ Scandinavia House': {
'Id': 28492,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Shabu Shabu Kobe': {
'Id': 168913,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Seven Bistro': {
'Id': 34375,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Maru Karaoke Lounge': {
'Id': 115909,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Kun Jip': {
'Id': 237652,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'Kyochon': {
'Id': 57898,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'O\'Reilly\'s Bar & Kitchen': {
'Id': 95806,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Kristalbelli': {
'Id': 76810,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Keens Steakhouse': {
'Id': 450,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'The Crooked Knife': {
'Id': 53365,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Cho Dang Gol Korean Restaurant': {
'Id': 237985,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'Kirakuya': {
'Id': 98149,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'John Doe Bar & Kitchen': {
'Id': 211981,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Shabu Shabu Kobe': {
'Id': 168913,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Koi - Bryant Park': {
'Id': 4035,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Hakubai - The Kitano': {
'Id': 46417,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Delmonico\'s Kitchen': {
'Id': 38689,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Cask Bar & Kitchen': {
'Id': 101434,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Foley\'s NY': {
'Id': 237397,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'Chorus NYC': {
'Id': 227827,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'IchiUmi - NYC': {
'Id': 211564,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Nelly Spillanes': {
'Id': 261511,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Her Name is Han': {
'Id': 212356,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Shilla - NY': {
'Id': 237658,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'Madangsui-NY': {
'Id': 161317,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'The Liberty NYC': {
'Id': 103831,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'The NoMad': {
'Id': 78730,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Pennsylvania 6 - NYC': {
'Id': 92527,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Sushi Sen-nin': {
'Id': 235423,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'The Smith - Nomad': {
'Id': 193615,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Niles New York City': {
'Id': 38500,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Havana NY': {
'Id': 27934,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Izakaya NoMad': {
'Id': 149746,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Wonjo': {
'Id': 244678,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'AYZA Wine & Chocolate Bar': {
'Id': 33382,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Don\'s Bogam BBQ & Wine Bar': {
'Id': 111265,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'L&W Oyster Co': {
'Id': 96586,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'PN wood fired pizza': {
'Id': 269497,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Wine 30': {
'Id': 57103,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Wolfgang\'s Steak House - Park Avenue': {
'Id': 3603,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Wine 34': {
'Id': 210874,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Proper West': {
'Id': 161812,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Wine Disciples Enoteca - Permanently Closed': {
'Id': 174346,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Lallisse Mediterranean Wine & Food': {
'Id': 54622,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Tiffin Wallah': {
'Id': 61213,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Pig n Whistle on 36th': {
'Id': 66772,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'American Whiskey': {
'Id': 112468,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Whitman and Bloom': {
'Id': 112306,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Heartland Brewery - Empire State Building': {
'Id': 148705,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Avaton Estiatorio': {
'Id': 169447,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'28th Street Tarallucci e Vino': {
'Id': 261748,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Wine Disciples Enoteca - Permanently Closed': {
'Id': 174346,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Eleven Madison Park': {
'Id': 211,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Baita at La Birreria - Eataly NYC Flatiron': {
'Id': 152821,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Lalibela Ethiopian Restaurant': {
'Id': 246469,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Eros Restaurant (fka Ethos Taverna)': {
'Id': 15580,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Manzo Ristorante - Eataly NYC Flatiron': {
'Id': 51274,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Coppola\'s East': {
'Id': 75208,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Pranzo - Eataly NYC Flatiron - Permanently Closed': {
'Id': 152833,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'El Rio Grande': {
'Id': 16822,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'La Pizza & La Pasta - Eataly NYC Flatiron': {
'Id': 152827,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Obica Mozzarella Bar  Pizza e Cucina': {
'Id': 146161,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Evergreen on 38': {
'Id': 248356,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'Parker & Quinn': {
'Id': 102817,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Restaurant Patrick at Club Quarters': {
'Id': 162841,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'El Quinto Pino': {
'Id': 148285,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Le Pain Quotidien - Flatiron': {
'Id': 252733,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Mighty Quinn\'s Barbeque': {
'Id': 161833,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 412, 'Name': 'West Village' } },
'Quality Italian': {
'Id': 110224,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Quinn\'s': {
'Id': 296317,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Quality Meats': {
'Id': 6438,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'The Quarter': {
'Id': 103345,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 111, 'Name': 'Greenwich Village' } },
'Qi': {
'Id': 237334,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 443, 'Name': 'Union Square' } },
'Queen of the Night at The Diamond Horseshoe - Permanently Closed': {
'Id': 148804,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Queen of Sheba': {
'Id': 237382,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 454, 'Name': 'Hell\'s Kitchen' } },
'House of Que': {
'Id': 193609,
'Type': 'Restaurant',
'Region': { 'Id': 22, 'Name': 'New Jersey - North' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 461, 'Name': 'Hoboken' } },
'Quartino': {
'Id': 217909,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 604, 'Name': 'NoHo' } },
'Le Pain Quotidien - Bleecker Street': {
'Id': 252730,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 604, 'Name': 'NoHo' } },
'State Grill and Bar': {
'Id': 150565,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Heartland Brewery - Empire State Building': {
'Id': 148705,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'AYZA Wine & Chocolate Bar': {
'Id': 33382,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Ben and Jack\'s on 5th Avenue': {
'Id': 32191,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Habanero Blues': {
'Id': 267613,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Strand Bistro at Marriott Vacation Club Pulse': {
'Id': 47467,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'David Burke fabrick': {
'Id': 144487,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Madison Bistro': {
'Id': 2587,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Belgian Beer Cafe NoMad': {
'Id': 151012,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Black Barn': {
'Id': 5337,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 523, 'Name': 'NoMad' } },
'Hill Country BBQ Market - Flatiron': {
'Id': 24202,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Brother Jimmy\'s - Murray Hill': {
'Id': 25408,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Koi - Bryant Park': {
'Id': 4035,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Bryant Park Grill': {
'Id': 12019,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Seven Bistro': {
'Id': 34375,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'The Liberty NYC': {
'Id': 103831,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'L\'Amico': {
'Id': 186856,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Monarch Rooftop Lounge': {
'Id': 172018,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'L&W Oyster Co': {
'Id': 96586,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Suite 36 Restaurant & Sports Lounge': {
'Id': 108868,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'La Pecora Bianca': {
'Id': 189079,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Lugo Cucina': {
'Id': 2394,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Toshi\'s Living Room & Penthouse': {
'Id': 139150,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Les Halles Park Avenue - Permanently Closed': {
'Id': 16273,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Le Parisien': {
'Id': 57316,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Lallisse Mediterranean Wine & Food': {
'Id': 54622,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'La Tarte Flambee - Jardin': {
'Id': 148402,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'La Mesa de Paul Restaurant @ The Paul Hotel NYC': {
'Id': 190897,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Baita at La Birreria - Eataly NYC Flatiron': {
'Id': 152821,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'The Little Beet Table': {
'Id': 152188,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Pocha 32': {
'Id': 279994,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 412, 'Name': 'West Village' } },
'O\'Reilly\'s Pub': {
'Id': 211501,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'PN wood fired pizza': {
'Id': 269497,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Wolfgang\'s Steak House - Park Avenue': {
'Id': 3603,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Millesime - Permanently Closed': {
'Id': 49813,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Pondicheri Cafe': {
'Id': 266677,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Strand Bistro at Marriott Vacation Club Pulse': {
'Id': 47467,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Deweys Pub': {
'Id': 170032,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'La Pecora Bianca': {
'Id': 189079,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Toshi\'s Living Room & Penthouse': {
'Id': 139150,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Proper West': {
'Id': 161812,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Pranna - Permanently Closed': {
'Id': 15985,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Les Halles Park Avenue - Permanently Closed': {
'Id': 16273,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Park Avenue Autumn': {
'Id': 138868,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Koi - Bryant Park': {
'Id': 4035,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Foley\'s NY': {
'Id': 237397,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'Third Floor Cafe': {
'Id': 236980,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Ai Fiori': {
'Id': 52969,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'PN wood fired pizza': {
'Id': 269497,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Frankie & Johnnie\'s Steakhouse - Manhattan': {
'Id': 2792,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Feile': {
'Id': 64333,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'David Burke fabrick': {
'Id': 144487,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'The Flatiron Room': {
'Id': 100438,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Hill Country BBQ Market - Flatiron': {
'Id': 24202,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'230 FIFTH': {
'Id': 221146,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Flatiron Hall': {
'Id': 149302,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Franchia': {
'Id': 224974,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Lallisse Mediterranean Wine & Food': {
'Id': 54622,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'La Tarte Flambee - Jardin': {
'Id': 148402,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'The Shop - Andaz Fifth Avenue': {
'Id': 65509,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Up on 20 - Hyatt Herald Square': {
'Id': 173974,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Ulivo': {
'Id': 265465,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 523, 'Name': 'NoMad' } },
'Hotel Grand Union': {
'Id': 255670,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Upland': {
'Id': 151747,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Umi Japanese Restaurant': {
'Id': 257827,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Uncle Nick\'s Greek Cuisine - Chelsea': {
'Id': 67096,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Cafe Un Deux Trois': {
'Id': 84802,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Wined Up Wine Bar': {
'Id': 45325,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Uncle Jack\'s Steakhouse - Westside 9th Avenue': {
'Id': 2654,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Union Fare': {
'Id': 211969,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 443, 'Name': 'Union Square' } },
'Rosa Mexicano - Union Square': {
'Id': 4946,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 443, 'Name': 'Union Square' } },
'Utsav Indian Bar and Grill': {
'Id': 734,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'da Umberto': {
'Id': 108874,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Ushiwakamaru': {
'Id': 215644,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Pierre Loti Union Square': {
'Id': 62233,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 443, 'Name': 'Union Square' } },
'AYZA Wine & Chocolate Bar': {
'Id': 33382,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Maxwell\'s Chophouse': {
'Id': 269545,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 523, 'Name': 'NoMad' } },
'Millesime - Permanently Closed': {
'Id': 49813,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Pondicheri Cafe': {
'Id': 266677,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Strand Bistro at Marriott Vacation Club Pulse': {
'Id': 47467,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Chef 28': {
'Id': 167581,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Niles New York City': {
'Id': 38500,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Belgian Beer Cafe NoMad': {
'Id': 151012,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Calle Dao': {
'Id': 149428,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Lugo Cucina': {
'Id': 2394,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Hill Country BBQ Market - Flatiron': {
'Id': 24202,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Pranna - Permanently Closed': {
'Id': 15985,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Les Halles Park Avenue - Permanently Closed': {
'Id': 16273,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Smorgas Chef @ Scandinavia House': {
'Id': 28492,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Dos Caminos - Park': {
'Id': 30496,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Heartland Brewery - Empire State Building': {
'Id': 148705,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Soju Haus': {
'Id': 270343,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 523, 'Name': 'NoMad' } },
'Her Name is Han': {
'Id': 212356,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Up on 20 - Hyatt Herald Square': {
'Id': 173974,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Hangawi': {
'Id': 217876,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Cuisine\'s at Holiday Inn Midtown': {
'Id': 229876,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'The Den - Hyatt Herald Square': {
'Id': 172762,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Habanero Blues': {
'Id': 267613,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Wolfgang\'s Steak House - Park Avenue': {
'Id': 3603,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Reichenbach Hall': {
'Id': 171676,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Havana NY': {
'Id': 27934,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Hyo Dong Gak': {
'Id': 237601,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'Hooters on 33rd': {
'Id': 174256,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Hill Country BBQ Market - Flatiron': {
'Id': 24202,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Hanjan': {
'Id': 169873,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Massoni': {
'Id': 324202,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Madangsui-NY': {
'Id': 161317,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Monarch Rooftop Lounge': {
'Id': 172018,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Ainsworth Midtown': {
'Id': 142273,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'5th & MAD': {
'Id': 171055,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Ravagh - Madison Avenue': {
'Id': 226105,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Marta': {
'Id': 151072,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Mason Jar': {
'Id': 51826,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Frankie & Johnnie\'s Steakhouse - Manhattan': {
'Id': 2792,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Maxwell\'s Chophouse': {
'Id': 269545,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 523, 'Name': 'NoMad' } },
'Millesime - Permanently Closed': {
'Id': 49813,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Strand Bistro at Marriott Vacation Club Pulse': {
'Id': 47467,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Madison Bistro': {
'Id': 2587,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Maysville': {
'Id': 95353,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Marcony': {
'Id': 41878,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Niles New York City': {
'Id': 38500,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'o ya - NYC': {
'Id': 167146,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Nick and Stef\'s Steakhouse - New York': {
'Id': 2216,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Yamato Ramen': {
'Id': 333877,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'New York Central': {
'Id': 51208,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Novita - New York City, Manhattan': {
'Id': 30202,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Public House - New York': {
'Id': 12487,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Tommy Bahama - New York': {
'Id': 94612,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Drag Brunch at Hard Rock Cafe - New York': {
'Id': 261628,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Yakiniku Futago': {
'Id': 168805,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 443, 'Name': 'Union Square' } },
'Hakkasan - New York': {
'Id': 83344,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Blue Fin - New York': {
'Id': 30505,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Freds Downtown at Barneys New York': {
'Id': 212974,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'The New York Beer Company': {
'Id': 77902,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 454, 'Name': 'Hell\'s Kitchen' } },
'Outback Steakhouse - New York': {
'Id': 314209,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Kun Jip': {
'Id': 237652,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'Jack Demsey\'s': {
'Id': 242350,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 6731, 'Name': 'Flower District' } },
'Juni - Permanently Closed': {
'Id': 106966,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Ben and Jack\'s on 5th Avenue': {
'Id': 32191,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Mason Jar': {
'Id': 51826,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Frankie & Johnnie\'s Steakhouse - Manhattan': {
'Id': 2792,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'John Doe Bar & Kitchen': {
'Id': 211981,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Zuma Japanese Restaurant - NY': {
'Id': 162010,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Brother Jimmy\'s - Murray Hill': {
'Id': 25408,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'La Tarte Flambee - Jardin': {
'Id': 148402,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Junoon Main Dining Room': {
'Id': 54115,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Junoon Patiala Room': {
'Id': 265027,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Jimmy\'s NYC': {
'Id': 342013,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Jack\'s Restaurant & Bar - NYC': {
'Id': 34114,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 202, 'Name': 'Theater District / Times Square' } },
'Umi Japanese Restaurant': {
'Id': 257827,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Third Floor Cafe': {
'Id': 236980,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Trademark': {
'Id': 215011,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Spoon Table & Bar': {
'Id': 108598,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'Stella 34 Trattoria': {
'Id': 102115,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 118, 'Name': 'Midtown West' } },
'Toledo Restaurant': {
'Id': 144997,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'TEISUI': {
'Id': 191173,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Tavern 29': {
'Id': 79678,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Till & Sprocket': {
'Id': 214435,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 195, 'Name': 'Chelsea' } },
'Toshi\'s Living Room & Penthouse': {
'Id': 139150,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'Trattoria Belvedere': {
'Id': 61435,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Black Barn Chef\'s Table': {
'Id': 192076,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 523, 'Name': 'NoMad' } },
'Bread & Tulips': {
'Id': 64252,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 163, 'Name': 'Gramercy / Flatiron' } },
'La Tarte Flambee - Jardin': {
'Id': 148402,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 119, 'Name': 'Midtown East' } },
'I Trulli': {
'Id': 124,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } },
'Tiffin Wallah': {
'Id': 61213,
'Type': 'Restaurant',
'Region': { 'Id': 16, 'Name': 'Manhattan' },
'Metro': { 'Id': 8, 'Name': 'New York / Tri-State Area' },
'Country': 'United States',
'Neighborhood': { 'Id': 110, 'Name': 'Murray Hill' } }
}
