language: python
python:
  - "2.7"
env:
  - DATABASE_URL='sqlite:///:memory:'

# command to install dependencies
install: 
  - pip install --egg -r requirements.txt
  - pip install coveralls
  - python manage.py create_db
# command to run tests
script: 
  - coverage run --branch --include=application/app.py,application/models.py,application/utils/auth.py  test.py tests/
after_success:
  - coveralls

