language: python
python:
  - "2.7"
env:
  - DATABASE_URL='sqlite:///:memory:'

# command to install dependencies
install: 
  - pip install --egg -r requirements.txt
  - python manage.py create_db
# command to run tests
script: 
  - python test.py
after_success:
  - coveralls

