language: python
python:
  - "2.7"
env:
  - WEBDIR=static
# command to install dependencies
install: 
  - pip install --egg -r requirements.txt
  - cd $WEBDIR && npm install
# command to run tests
script: 
  - python test.py
  - cd $WEBDIR && npm run-script test

