language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - cd static && npm install && cd ..
  - pip install -r requirements.txt
# command to run tests
script: 
  - python test.py
  - cd static && npm run-script test && cd ..

